### ISSUE TITLE
No button provided for slot deletion

### ISSUE THREAD

**Issue by bravo-stack** [booluw/slot#2]
I have carefully checked and searched to see if there's a button hidden somewhere, that allows a user to delete a slot, but it appears there isn't. 
![Screenshot_20220121-130922](https://user-images.githubusercontent.com/83971191/150524870-b7431892-1c49-4f11-8035-fabb4585729f.png)
![Screenshot_20220121-130932](https://user-images.githubusercontent.com/83971191/150524881-4f223223-74ac-47dc-b412-6ff11b99e48e.png)
![Screenshot_20220121-130945](https://user-images.githubusercontent.com/83971191/150524884-198b48de-1b83-4f5d-a984-97800e5647db.png)

**Comment by booluw** [comment]
@bravo-stack, there surely won't be a need to share images here.
The _delete button_ isn't a piority at the moment. Experinces aren't meant to be deleted, no matter how bad they might seem.
Future version might reconsider this tho. Cheers.
