### ISSUE TITLE
(Bug) Signs me out without my approval

### ISSUE THREAD

**Issue by bravo-stack** [booluw/slot#3]
When I clicked on the sign out button located at the bottom, a modal popped up for confirmation, then I click on the background which isn't supposed to sign me out. Instead, I get signed out.

**Comment by booluw** [comment]
This has to do with _sweetalerts_. Would go through the docs again if there is any fix for that, there should be lol.

**Comment by booluw** [comment]
Fixed on the latest update.
Now: User can choose to log out or click outside the alert to not do so.
